baseURL = "https://pawprintprototyping.org/"
languageCode = "en-us"
title = "Pawprint Prototyping"
theme = "airspace-hugo"
# post pagination
pagination.pagerSize = "4"

################################# Outputs #################################
# hugo outputs
[outputs]
home = [ "HTML", "RSS"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/spacestatus/spacestatus.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[[params.plugins.js]]
link = "plugins/spacestatus/spacestatus.js"


############################### widgets #################################

[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "Pawprint Prototyping is a non-profit hackerspace in Santa Clara with furry flair"
author = "Pawprint Prototyping"
# Contact Information
mobile = "(669) 696-7297"
email = "info [at] pawprintprototyping [dot] org"
location = "545 Aldo Ave #24, Santa Clara, CA 95054"
phone = "(669) 696-7297"
# contact form action
contact_form_action = "https://formspree.io/f/mpzorqev" # contact form works with : https://formspree.io
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false
# copyright
copyright = """\

"""

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Contact Us"
link = "contact"

# google map
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "37.385768"
map_longitude = "-121.9487897"
map_marker = "images/marker.png"

[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

######################### english navigation #############################
# main menu
[[Languages.en.menu.main]]
name = "Home"
URL = "/"
weight = 1

[[Languages.en.menu.main]]
name = "Calendar"
URL = "/pages/calendar"
weight = 2

[[Languages.en.menu.main]]
name = "Events"
URL = "https://events.pawprintprototyping.org"
weight = 3

[[Languages.en.menu.main]]
name = "Donate"
URL = "/pages/donate"
weight = 4

[[Languages.en.menu.main]]
name = "Wiki"
URL = "https://wiki.pawprint.space/"
weight = 5

[[Languages.en.menu.main]]
name = "Blog"
URL = "blog"
weight = 6

#[[Languages.en.menu.main]]
#weight = 6
#name = "Pages"
#hasChildren = true

[[Languages.en.menu.main]]
name = "FAQ"
URL = "/faq"
weight = 7


#  #[[Languages.en.menu.main]]
#  #parent = "Pages"
#  #name = "Pricing"
#  #URL = "pricing"

[[Languages.en.menu.main]]
name = "Bylaws"
URL = "/pages/bylaws"
weight = 7


[[Languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 9

[[Languages.en.menu.main]]
name = "Status"
id = "spaceswitch"
pre = '<span id="spacestatus" class=""></i></span>'
URL = "https://wiki.pawprint.space/space_switch/"
weight = 10

# footer menu
[[Languages.en.menu.footer]]
name = "About"
URL = "about"
weight = 1

[[Languages.en.menu.footer]]
name = "Governance"
URL = "https://github.com/PawprintPrototyping/admin"
weight = 2

#[[Languages.en.menu.footer]]
#name = "Service"
#URL = "service"
#weight = 3

#[[Languages.en.menu.footer]]
#name = "Pricing"
#URL = "pricing"
#weight = 4

#[[Languages.en.menu.footer]]
#name = "FAQ"
#URL = "faq"
#weight = 5

[[Languages.en.menu.footer]]
name = "Contact Us"
URL = "contact"
weight = 6
